name: InterMine WS Python CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      # Label used to access the service container
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432/tcp
    env:
      TESTMODEL_URL: http://localhost:8080/intermine-demo
      TESTMODEL_PATH: intermine-demo
    steps:
    - uses: actions/checkout@v2
    - name: Set up python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install PostgreSQL client
      run: |
        sudo apt-get update -y
        sudo apt-get install -y libpq-dev postgresql-client
        sudo service postgresql start
    - name: Run unit tests
      run: ./config/ci/init-solr.sh && ./config/ci/init.sh && python setup.py test && python setup.py livetest
